name: atomsbox_news_app
description: A News app made with Flutter using atomsbox
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  atomsbox: ^0.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2  
  google_fonts: ^4.0.3
  go_router: ^6.0.1
  json_annotation: ^4.8.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true


